config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :tasks, except: [:show] do
    collection do
      get 'main'
    end
  end

  resources :routines, except: [:show]

  resources :statuses, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/routine.rb
class Routine < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :routines
  has_one :status
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/routines_controller.rb
class RoutinesController < ApplicationController
  before_action :set_routine, only: [:edit, :update, :destroy]
  before_action :prohibit_create_routine, only: [:new]

  def index
    @routines = Routine.where(user_id: current_user.id)
  end

  def new
    @routine = Routine.new
  end

  def create
    @routine = Routine.new(routine_params)
    
    if @routine.save
      render :create
      return
    else
      flash[:alert] = "ルーティンを追加できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  def edit
  end

  def update
    if @routine.update(routine_params)
      render :update
      return
    else
      flash[:alert] = "ルーティンを編集できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  def destroy
    if @routine.destroy
      render :destroy
      return
    else
      flash[:alert] = "ルーティンを編集できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  private

  def routine_params
    params.require(:routine).permit(:user_id, :content)
  end

  def set_routine
    @routine = Routine.find(params[:id])
  end

  def prohibit_create_routine
    @maximum_num = 5
    @routines = Routine.where(user_id: current_user.id)

    if @routines.length >= @maximum_num
      flash[:alert] = "作成できるルーティンの数は#{@maximum_num}個までです"
      redirect_to main_tasks_path
    else
      # nop
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def new
    @status = Status.where(user_id: current_user.id)

    completes = Task.where(user_id: current_user.id, is_complete: true)
    @total_points = 0
    completes.each do |complete|
      @total_points = @total_points + complete.point
    end

    if @status.blank?
      @status = Status.new
    else
      redirect_to action: :edit, id: @status.ids
      return
    end
  end

  def create
    @status = Status.new(status_params)

    if @status.save
      flash[:notice] = "ステータスを編集しました"
    else
      flash[:alert] = "ステータスの編集に失敗しました"
    end

    redirect_to main_tasks_path
    return
  end

  def edit
    @status = Status.find(params[:id])

    completes = Task.where(user_id: current_user.id, is_complete: true)
    @total_points = 0
    completes.each do |complete|
      @total_points = @total_points + complete.point
    end

    if @status.blank?
      redirect_to action: new
      return
    else
      # nop
    end
  end

  def update
    @status = Status.find(params[:id])

    if @status.update(status_params)
      flash[:notice] = "ステータスを編集しました"
    else
      flash[:alert] = "ステータスの編集に失敗しました"
    end

    redirect_to main_tasks_path
    return
  end

  private
  
  def status_params
    params.require(:status).permit(:user_id, :heart, :attack, :defense)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:main]
  before_action :set_task, only: [:edit, :update, :destroy]

  def index
    @routine_tasks = Task.where(user_id: current_user.id, classification_id: 1, deadline: Time.current.end_of_day).order("created_at DESC")

    @q = Task.where(user_id: current_user.id, classification_id: 2).ransack(params[:q])
    @q.sorts = 'created_at DESC' if @q.sorts.empty?
    @todo_tasks = @q.result(distinct: true)
    @maximum_per_page = 100

    if @todo_tasks.length <= @maximum_per_page
      @results = @todo_tasks
    else
      @results = @todo_tasks.page(params[:page]).per(@maximum_per_page)
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    
    if @task.save
      render :create
      return
    else
      flash[:alert] = "タスクを追加できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      render :update
      return
    else
      flash[:alert] = "タスクを編集できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  def destroy
    if @task.destroy
      render :destroy
      return
    else
      flash[:alert] = "タスクを削除できませんでした"
      redirect_to main_tasks_path
      return
    end
  end

  def main
    # タスク表示
    @routine_tasks = Task.where(user_id: current_user.id, classification_id: 1, deadline: Time.current.end_of_day).order("created_at DESC")
    @todo_tasks    = Task.where(user_id: current_user.id, classification_id: 2).order("created_at DESC").first(5)

    # ユーザプロパティ表示
    completes      = Task.where(user_id: current_user.id, is_complete: true)
    @total_points = 0
    completes.each do |complete|
      @total_points = @total_points + complete.point
    end
    @level = (@total_points / 10) + 1
    @counter = 10 - (@total_points % 10)

    # ステータス表示
    status = Status.find_by(user_id: current_user.id)
    heart = 0
    attack = 0
    defense = 0
    if status
      heart = status.heart
      attack = status.attack
      defense = status.defense
    else
      # do nothing
    end
    @surplus = @total_points - (heart + attack + defense)
    @heart = heart + 10
    @attack = attack + 5
    @defense = defense + 5
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :content, :classification_id, :point, :deadline, :is_complete)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "UTF-8"}
    %meta(name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no") 
    %title Tasquest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      .header__title
        = link_to "tasquest", root_path
      .header__right
        - if user_signed_in?
          = link_to "セーブして終わる", destroy_user_session_path, method: :delete, class: "header__right__btn"
        - else
          = link_to "つづきから", new_user_session_path, class: "header__right__btn"
          = link_to "はじめから", new_user_registration_path, class: "header__right__btn"
    .contents
      = yield

app/views/routines/create.html.haml
.routines-success-page
  %h3<
    ルーティンを追加しました。
  = link_to routines_path do
    ルーティン一覧ページへ
  = link_to main_tasks_path do
    メインページへ
  = link_to new_routine_path do
    さらにルーティンを追加する

app/views/routines/destroy.html.haml
.routines-success-page
  %h3<
    ルーティンを削除しました。
  = link_to routines_path do
    ルーティン一覧ページへ
  = link_to main_tasks_path do
    メインページへ

app/views/routines/edit.html.haml
.routines-edit-page
  = form_with(model: @routine, local: true) do |f|
    %h3<
      ルーティンを編集する

    .routines-edit-page__label
      = f.label 'タスクの内容'
    .routines-edit-page__content
      = f.text_field :content, maxlength: 40

    .routines-edit-page__edit-btn
      = f.submit 'タスクを編集する'

    .routines-edit-page__return-btn
      = link_to main_tasks_path do
        メインページへ

app/views/routines/index.html.haml
.routines-index-page
  - if @routines.present?
    .routines-index-page__table
      %table
        %caption
          ルーティン一覧
        %tr
          %th
            タスクの内容
          %th
            編集
          %th
            削除
        - @routines.each do |routine|
          %tr
            %td
              = routine.content
            %td
              = link_to edit_routine_path(routine.id) do
                編集する
            %td
              = link_to "/routines/#{routine.id}", method: :delete do
                削除する
  - else
    .routines-index-page__message
      現在登録されているルーティンはありません

  .routines-index-page__add-btn
    = link_to new_routine_path do
      ルーティンを追加する

  .routines-index-page__return-btn
    = link_to main_tasks_path do
      メインページへ

app/views/routines/new.html.haml
.routines-new-page
  = form_with(model: @routine, local: true) do |f|
    %h3<
      タスクを追加する

    = f.hidden_field :user_id, value: current_user.id

    .routines-new-page__label
      = f.label 'タスクの内容'
    .routines-new-page__content
      = f.text_field :content, maxlength: 40

    .routines-new-page__add-btn
      = f.submit 'ルーティンを登録する'

    .routines-new-page__return-btn
      = link_to main_tasks_path do
        メインページへ

app/views/routines/update.html.haml
.routines-success-page
  %h3<
    ルーティンを編集しました。
  = link_to routines_path do
    ルーティン一覧ページへ
  = link_to main_tasks_path do
    メインページへ

app/views/statuses/_status-form.html.haml
= form_with model: @status do |f|

  = f.hidden_field :user_id, value: current_user.id

  .status__label
    = f.label '体力'
  .status__form
    = f.number_field :heart
    pt + (基礎体力10pt)

  .status__label
    = f.label '攻撃'
  .status__form
    = f.number_field :attack
    pt + (基礎攻撃5pt)

  .status__label
    = f.label '防御'
  .status__form
    = f.number_field :defense
    pt + (基礎防御5pt)

  #total-points
    = "#{@total_points}"

  .status__surplus
    = "残り#{@total_points}pt割り振りできます"

  .status__submit-btn
    = f.submit '割り振る'

app/views/statuses/edit.html.haml
.status
  = render "statuses/status-form"

app/views/statuses/new.html.haml
.status
  = render "statuses/status-form"

app/views/tasks/_flash_messages.html.haml
- if flash[:notice]
  .flash-notice
    = flash[:notice]
- else
  -# nop

- if flash[:alert]
  .flash-alert
    = flash[:alert]
- else
  -# nop

app/views/tasks/_left_contents.html.haml
.left-contents
  .left-contents__user-info
    .left-contents__user-info__basic
      .left-contents__user-info__basic__name
        = current_user.nickname
      = link_to edit_user_registration_path, class: "left-contents__user-info__basic__edit-user-btn" do
        ユーザー情報を変更する
    .left-contents__user-info__property
      .left-contents__user-info__property__num
        .left-contents__user-info__property__num__level
          = "Lv.#{@level}"
        .left-contents__user-info__property__num__point
          = "#{@total_points}pt"
      .left-contents__user-info__property__chart
        - case @counter
        - when 0 then
          ■ ■ ■ ■ ■ ■ ■ ■ ■ ■ 
        - when 1 then
          ■ ■ ■ ■ ■ ■ ■ ■ ■ □ 
        - when 2 then
          ■ ■ ■ ■ ■ ■ ■ ■ □ □ 
        - when 3 then
          ■ ■ ■ ■ ■ ■ ■ □ □ □ 
        - when 4 then
          ■ ■ ■ ■ ■ ■ □ □ □ □ 
        - when 5 then
          ■ ■ ■ ■ ■ □ □ □ □ □ 
        - when 6 then
          ■ ■ ■ ■ □ □ □ □ □ □ 
        - when 7 then
          ■ ■ ■ □ □ □ □ □ □ □ 
        - when 8 then
          ■ ■ □ □ □ □ □ □ □ □ 
        - when 9 then
          ■ □ □ □ □ □ □ □ □ □ 
        - when 10 then
          □ □ □ □ □ □ □ □ □ □ 
        - else
          □ □ □ □ □ □ □ □ □ □ 
      .left-contents__user-info__property__counter
        = "次のレベルまで #{@counter}pt"
    .left-contents__user-info__statuses
      %table.left-contents__user-info__statuses__status
        %tr
          %td
            HP
          %td
            = "#{@heart}pt"
        %tr
          %td
            攻撃
          %td
            = "#{@attack}pt"
        %tr
          %td
            防御
          %td
            = "#{@defense}pt"
      .left-contents__user-info__statuses__rest
        .left-contents__user-info__statuses__rest__counter
          = "割り振り可能:#{@surplus}pt"
        = link_to new_status_path, class: "left-contents__user-info__statuses__rest__deal-btn" do
          割り振る
    .left-contents__user-info__equipments
      %table.left-contents__user-info__equipments__equipment
        %tr
          %td
            武器
          %td
            ボーンソード
        %tr
          %td
            頭
          %td
            ボーンヘルム
        %tr
          %td
            胸
          %td
            ボーンメイル
        %tr
          %td
            腕
          %td
            ボーンアーム
        %tr
          %td
            腰
          %td
            ボーンコイル
        %tr
          %td
            足
          %td
            ボーングリーヴ
        %tr
          %td
            装飾品
          %td
            装備なし
  .left-contents__battle
    .left-contents__battle__degree
      初級
    = link_to "#", class: "left-contents__battle__challenge-battle-btn" do
      バトル

app/views/tasks/_right_contents.html.haml
.right-contents
  .right-contents__notice
    .right-contents__notice__title
      お知らせ
    %ul
      %li
        特になし
  .right-contents__routine-tasks
    .right-contents__routine-tasks__title
      ルーティンタスク
    .right-contents__routine-tasks__list
      %table
        %tr
          %th
            タスクの内容
          %th
            完了/未完了
        - @routine_tasks.each do |routine|
          %tr
            %td
              = routine.content
            %td
              - if routine.is_complete
                完了
              - else
                未完了
    .right-contents__routine-tasks__btns
      = link_to routines_path, class: "right-contents__routine-tasks__btns__routine-list-btn" do
        ルーティン一覧ページへ
      = link_to tasks_path, class: "right-contents__routine-tasks__btns__more-btn" do
        タスク一覧ページへ
  .right-contents__todo-tasks
    .right-contents__todo-tasks__title
      ToDoタスク
    .right-contents__todo-tasks__list
      %table
        %tr
          %th
            タスクの内容
          %th
            タスクの締め切り日時
          %th
            ポイント
          %th
            完了/未完了
        - @todo_tasks.each do |todo|
          %tr
            %td
              = todo.content
            %td
              = todo.deadline
            %td
              = "#{todo.point}pt"
            %td
              - if todo.is_complete
                完了
              - else
                未完了
    .right-contents__todo-tasks__btns
      = link_to new_task_path, class: "right-contents__todo-tasks__btns__add-task-btn" do
        タスクを追加する
      = link_to tasks_path, class: "right-contents__todo-tasks__btns__more-btn" do
        タスク一覧ページへ
  .right-contents__settings
    .right-contents__settings__title
      他サービスとの連携
    .right-contents__settings__btns
      = link_to "#", class: "right-contents__settings__btns__btn" do
        ガントチャート作成(仮)
      = link_to "#", class: "right-contents__settings__btns__btn" do
        Googleカレンダー連携(仮)

app/views/tasks/create.html.haml
.tasks-success-page
  %h3<
    タスクを追加しました。
  = link_to main_tasks_path do
    メインページへ
  = link_to new_task_path do
    さらにタスクを追加する

app/views/tasks/destroy.html.haml
.tasks-success-page
  %h3<
    タスクを削除しました。
  .tasks-success-page__return-btn
    = link_to tasks_path do
      タスク一覧ページへ
  = link_to main_tasks_path do
    メインページへ

app/views/tasks/edit.html.haml
.tasks-edit-page
  = form_with(model: @task, local: true) do |f|
    %h3<
      タスクを編集する

    - if @task.classification_id == 2
      .tasks-edit-page__label
        = f.label 'タスクの内容'
      .tasks-edit-page__content
        = f.text_field :content, maxlength: 40
      .tasks-edit-page__label
        = f.label 'ポイント'
      .tasks-edit-page__point
        = f.number_field :point, min: 1, max: 5

      .tasks-edit-page__label
        = f.label 'タスクの締め切り日時'
      .tasks-edit-page__deadline
        = f.datetime_field :deadline
    - else
      -# nop

    .tasks-edit-page__label
      = f.label '完了/未完了'
    .tasks-edit-page__complete
      = f.radio_button :is_complete, 'true'
      完了
      = f.radio_button :is_complete, 'false'
      未完了

    .tasks-edit-page__edit-btn
      = f.submit 'タスクを編集する'

    .tasks-edit-page__return-btn
      = link_to tasks_path do
        タスク一覧ページへ

app/views/tasks/index.html.haml
.search-contents
  .search-contents__forms
    = search_form_for @q do |f|
      .search-contents__forms__form
        .search-contents__forms__form__label
          = f.label :content, 'タスクの内容'
        .search-contents__forms__form__field
          = f.search_field :content_cont
        .search-contents__forms__form__label
          = f.label :is_complete, '完了/未完了'
        .search-contents__forms__form__field
          = f.radio_button :is_complete_eq, '', { :checked => true }
          指定なし
          = f.radio_button :is_complete_eq, 'true'
          完了
          = f.radio_button :is_complete_eq, 'false'
          未完了
      .search-contents__forms__submit-btn
        = f.submit '検索する'
  - if @routine_tasks.present?
    .search-contents__results
      %table
        %caption
          ルーティンタスク
        %tr
          %th
            タスクの内容
          %th
            完了/未完了
          %th
            編集
        - @routine_tasks.each do |routine|
          %tr
            %td
              = routine.content
            %td
              - if routine.is_complete
                完了
              - else
                未完了
            %td
              = link_to edit_task_path(routine.id) do
                編集する
  - else
    .search-contents__message
      現在登録されているルーティンタスクはありません
  - if @todo_tasks.present?
    .search-contents__results
      %table
        %caption
          ToDoタスク
        %tr
          %th
            タスクの内容
          %th
            タスクの締め切り日時
          %th
            ポイント
          %th
            完了/未完了
          %th
            編集
          %th
            削除
        - @results.each do |result|
          %tr
            %td
              = result.content
            %td
              = result.deadline
            %td
              = "#{result.point}pt"
            %td
              - if result.is_complete
                完了
              - else
                未完了
            %td
              = link_to edit_task_path(result.id) do
                編集する
            %td
              = link_to "/tasks/#{result.id}", method: :delete do
                削除する
    - if @todo_tasks.length > @maximum_per_page
      .search-contents__paginate
        = paginate(@results)
    - else
      -# nop
  - else
    .search-contents__message
      条件に一致するタスクはありませんでした

  .search-contents__return-btn
    = link_to main_tasks_path do
      メインページへ

app/views/tasks/main.html.haml
.tasks-wrapper
  = render "flash_messages"
  = render "left_contents"
  = render "right_contents"

app/views/tasks/new.html.haml
.tasks-new-page
  = form_with(model: @task, local: true) do |f|
    %h3<
      タスクを追加する

    = f.hidden_field :user_id, value: current_user.id

    = f.hidden_field :classification_id, value: 2

    .tasks-new-page__label
      = f.label 'タスクの内容'
    .tasks-new-page__content
      = f.text_field :content, maxlength: 40

    .tasks-new-page__label
      = f.label 'ポイント'
    .tasks-new-page__point
      = f.number_field :point, min: 1, max: 5

    .tasks-new-page__label
      = f.label 'タスクの締め切り日時'
    .tasks-new-page__deadline
      = f.datetime_field :deadline

    = f.hidden_field :is_complete, value: false

    .tasks-new-page__add-btn
      = f.submit 'タスクを登録する'

    .tasks-new-page__return-btn
      = link_to tasks_path do
        タスク一覧ページへ

app/views/tasks/update.html.haml
.tasks-success-page
  %h3<
    タスクを編集しました。
  = link_to main_tasks_path do
    メインページへ

app/views/top/_contents.html.haml
.top-page-contents
  .top-page-contents__introduce
    現実世界のタスクを管理しながら最強の勇者を育成しよう！
  .top-page-contents__start-btn
    = link_to "タスク管理", main_tasks_path

app/views/top/index.html.haml
.top-page-wrapper
  = render "contents"